# Generated by Django 3.1 on 2021-06-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('address', models.CharField(max_length=200)),
                ('googlemaps', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='', max_length=2)),
            ],
        ),
    ]
