# Generated by Django 3.1 on 2021-06-18 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20210618_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.country'),
        ),
    ]
